# yaml-language-server: $schema=https://cdn.jsdelivr.net/npm/rollhook/schema/config.json
apps:
  - name: my-api
    compose_path: /srv/stacks/my-api/compose.yml
    steps:
      - service: backend
  - name: my-frontend
    compose_path: /srv/stacks/my-frontend/compose.yml
    steps:
      - service: frontend
